# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_book_subcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subcode',
            field=models.ForeignKey(default='F', on_delete=django.db.models.deletion.CASCADE, to='data.Subject'),
        ),
    ]
