# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20161126_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subcode',
        ),
    ]
