# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_book_subcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subcode',
        ),
    ]
