# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20161204_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
