# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20161204_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
